# Generated by Django 4.2.16 on 2024-10-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_bookings_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='expire_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateField(),
        ),
    ]
